### ISSUE TITLE
Melange Preferences

### ISSUE THREAD

**Issue by tdegueul** [diverse-project/melange#23]
It would be handy to be able to enable/disable the most time-consuming tasks (Eclipse projects generation, interfaces serialization, etc.) through a dedicated Eclipse Preferences page.

**Comment by barais** [comment]
It is quite easy to do, you can look at the code of kevoree eclipse plugin
to get a working example

2015-03-10 10:06 GMT+01:00 tdegueul notifications@github.com:

**Comment by tdegueul** [comment]
Done
