### ISSUE TITLE
Merging aspect .class directly into the EMFRuntime + using annotaiton to implement native emf operation

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/melange#27]
when using the creation of a metamodel such as
metamodel TfsmExtended inherits SimpleTfsm {
    exactType TfsmExtendedMT uri "http://tfsm/mt"
    with TFSMAspect
    with StateAspect
    with TransitionAspect
    with FSMClockAspect
    with EvaluateGuardAspect
}

it creates 2 projects: one for the EMFRuntime for TfsmExtended  and one containing a copied of the *Aspect classes adapted for TfsmExtended  .
since the adaptation works on java files only and not directly on xtend files we don't have the limitation prevent us to put all this in the same project. (see k3AL/xtend current limitation)

Then, if both emf generated code and behavior implementation code (from aspects) are in the same project,  it would be quite easy to modify the .ecore and add the correct annotation that will allow to generate the code that calls the aspect operations directly from the operation in the EObjects.

If the user wish to create new aspects or overide the behavior, he is free to create a dedicated aspect project...

**Comment by tdegueul** [comment]
This is now fixed: we generate one project per runtime language.
