### ISSUE TITLE
Specify file extension for models conforming to a language

### ISSUE THREAD

**Issue by tdegueul** [diverse-project/melange#43]
In Melange, we never explicitly set the file extension to be used by models conforming to a given language. EMF implicitly uses the name of the root package as the file extension.

Since the same Ecore file can be imported in various Melange languages, this can lead to conflicts. In this case, when Melange generates their runtime, they would use the same file extension, even though they are conceptually different.

To solve this problem, we can set an explicit file extension in the `.genmodel` generated from a language (each `GenPackage`has a `fileExtension`property). A good default would be to use the name of the language (in lower case) as the default file extension for its models. it would also be handy to be able to explicitly set the file extension of a language when needed. This means extending the current grammar with a new keyword (eg. `fileExtension X`).

See https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange/src/main/java/fr/inria/diverse/melange/ast/MetamodelExtensions.xtend#L66-L92 to set the file extension in the serialized `GenModel`.

**Comment by fcoulon** [comment]
Done in 4efb85cff768b98995fc41105a39d45c56993238
