### ISSUE TITLE
Generate Language runtime doesn't maintain the previous location on disk : lead to trouble when using git

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/melange#49]
when doing a generate Language runtime it completly remove any existing project. then recreate the project in the workspace.
The issue occurs when the previous project was actually imported in the workspace (because it is under version control with git for example) in that case, the synchronization with git is lost

**Comment by dvojtise** [comment]
this one seems to be fixed with Thomas's latest merge

**Comment by fcoulon** [comment]
Yes cleanAll is not longer performed at the beginning of the generateAll
