### ISSUE TITLE
generated nsURI of runtime model is too short when playing with languages variant in the same workspace

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/melange#60]
the generated nsURI is always 
`http://language_name/root_package/`
but it would be much better to use 
`http://full_language_name/root_package/`

for example in my language
`package org.gemoc.sample.tfsm.sequential
language XTfsm {
...
}
`

I expect the nsURI to be
`http://org.gemoc.sample.tfsm.sequential.xtfsm/tfsm/`
instead of
org.gemoc.sample.tfsm.sequential
`http://xtfsm/tfsm/`

because it may conflict the concurrent version

(note, I can workaround with a longer name but it will contain redundant information with the namespace)

this is annoying as there is also issue #59 which is related to that too.

**Comment by ebousse** [comment]
+1, complete uris would be cool

**Comment by tdegueul** [comment]
+1

This may break many (all?) of our examples though (at least the pure Melange ones, I guess it's the same for GEMOC). This should be taken care of.

**Comment by dvojtise** [comment]
Closing this. In recent version, the nsURIs seem to be OK in both model type an language runtime.
