### ISSUE TITLE
manifest update generates a Export-Package on a single line

### ISSUE THREAD

**Issue by awortmann** [diverse-project/melange#71]
when updating the manifest, melange generates a package export-package entry on a single line, this is fine for small projects, but creates invalid manifest files when there are a lot exported packages ...

**Comment by fcoulon** [comment]
Seems related to GemocSequentialLanguageBuilder.

@dvojtise 
Maybe we need to manage Export-packages here ?
https://github.com/diverse-project/tools/blob/master/commons-eclipse/fr.inria.diverse.commons.eclipse.pde/src/fr/inria/diverse/commons/eclipse/pde/manifest/ManifestChanger.java#L62

**Comment by dvojtise** [comment]
Yes indeed

may be this is also the place of the problem that occurs on some system that double the line break in the require-bundle, it should use the system separator in all the file.

**Comment by dvojtise** [comment]
This issue was moved to gemoc/gemoc-studio#35
