### ISSUE TITLE
Annoying output in tests

### ISSUE THREAD

**Issue by tdegueul** [diverse-project/melange#92]
Is there any reason to have this debug message? It's quite annoying in the test phase.

https://github.com/diverse-project/melange/blob/0456ec4dde6df19c89832d621aa725126f4b7fb5/plugins/fr.inria.diverse.melange/src/main/java/fr/inria/diverse/melange/ast/ModelTypeExtensions.xtend#L62

**Comment by fcoulon** [comment]
I introduce it in da70b49717bcc4871162ffdfd3a7e93871d58469 to have a clearer information (we printed the NPE stack before)

But I guess we can fail silently since Melange is not intended to work in standalone anymore

**Comment by dvojtise** [comment]
why does it use `println` instead of the logger that is available in the same class ?
