### ISSUE TITLE
useless addition of xtend-gen in new Melange project wizard

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/melange#93]
When creating a new melange project, the template (https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange.ui/src/main/java/fr/inria/diverse/melange/ui/wizards/MelangeFilesTemplates.xtend) uses:
```
source.. = src/,\
			           src-gen/,\
			           xtend-gen/
```
but xtend-gen is not added in the java sources (classpath) in https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange.ui/src/main/java/fr/inria/diverse/melange/ui/wizards/NewMelangeProjectWizard.java#L289

so we get a warning in the build.properties

we should either remove xtend-gen from the build.properties template or add it to the java sources in the classpath

**Comment by fcoulon** [comment]
Yep you're right. There is no Xtend files inside a new Melange project.
