### ISSUE TITLE
Obsolete IEventManager references

### ISSUE THREAD

**Issue by tdegueul** [diverse-project/melange#94]
`IEventManager` has disappeared from K3, but we still generate code that relies on it in Melange:

https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange/src/main/java/fr/inria/diverse/melange/utils/DispatchOverrider.xtend#L424-L427

Is it safe to remove these lines?

**Comment by fcoulon** [comment]
Yes I guess. The idea was the rewrite the dispatch generated by K3 to take in account new overridings from Aspects.

It was almost copied/pasted from https://github.com/diverse-project/melange/blob/master/plugins/fr.inria.diverse.melange/src/main/java/fr/inria/diverse/melange/utils/DispatchOverrider.xtend#L408

**Comment by d-leroy** [comment]
Indeed, it was an oversight from my part, I deleted the lines
